### ISSUE TITLE
check for phpcs.xml in project

### ISSUE THREAD

**Issue by UziTech** [jcartledge/atom-phpcbf#7]
This should check for phpcs.xml or phpcs.ruleset.xml in the project directory like linter-phpcs

**Comment by jcartledge** [comment]
Hi - can you point me to where that feature is documented? I'm not aware of it. Thanks.

**Comment by UziTech** [comment]
https://github.com/AtomLinter/linter-phpcs/blob/master/lib/main.coffee#L110

Here is where they implement it

**Comment by jcartledge** [comment]
This looks like it could be useful, but it's not something I have any use for at the moment, and I'm not really into reverse engineering the spec from the linter-phpcs implementation.

Happy to review a pull request if you (or anyone else) want to provide one.
